spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beom
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: duatmdqja09


  mail:
    host: smtp.gmail.com
    port: 587
    username: umcmariajeu@gmail.com
    password: wvvzrfbxvjumibrp
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
        debug: true




  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  servlet:
    encoding:
      force-response: true

jwt:
  token:
    secret: "IzesBluyiKsuIHpSBPPcFUFngHuwDagp"

springdoc:
  swagger-ui:
    path: /
    operations-sorter: alpha
    display-request-duration: true